# Generated by Django 5.0.4 on 2024-04-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='R1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ім_я', models.CharField(max_length=50)),
                ('Прізвище', models.CharField(max_length=50)),
                ('Дата_народження', models.DateField()),
                ('Стать', models.CharField(max_length=10)),
                ('Електронна_пошта', models.CharField(max_length=100)),
                ('Місце_проживання', models.CharField(default='Unknown', max_length=100)),
                ('Ціль', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='R10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Кількість_калорій', models.IntegerField()),
                ('Вміст_білків', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Вміст_жирів', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Вміст_вуглеводів', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Вміст_клітковини', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Дата', models.DateField()),
                ('Настрій', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='R11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Дата', models.DateField()),
                ('Настрій', models.CharField(max_length=50)),
                ('Рівень_енергії', models.CharField(max_length=50)),
                ('Симптом', models.TextField()),
                ('Дата_сну', models.DateField()),
                ('Час_засинання', models.TimeField()),
                ('Час_пробудження', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='R12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Симптом', models.TextField()),
                ('Прийняті_ліки', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='R13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Дата_сну', models.DateField()),
                ('Час_засинання', models.TimeField()),
                ('Час_пробудження', models.TimeField()),
                ('Тривалість_сну', models.DurationField()),
                ('Ім_я', models.CharField(max_length=50)),
                ('Прізвище', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='R14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Тривалість_сну', models.DurationField()),
                ('Якість_сну', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='R2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Опис_цілі', models.TextField()),
                ('Дата_початку', models.DateField()),
                ('Дата_завершення', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='R3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Опис_цілі', models.TextField()),
                ('Тип_цілі', models.CharField(max_length=50)),
                ('Зріст', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Вага', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='R4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Дата_початку', models.DateField()),
                ('Дата_завершення', models.DateField()),
                ('Статус', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='R5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Зріст', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Вага', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Кров_яний_тиск', models.CharField(max_length=20)),
                ('Відсоток_жиру_в_тілі', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Рівень_холестерину', models.CharField(max_length=20)),
                ('Індекс_маси_тіла', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Тип_активності', models.CharField(max_length=100)),
                ('Дата_проведення_активності', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='R6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Тип_активності', models.CharField(max_length=100)),
                ('Тривалість', models.DurationField()),
                ('Дата_проведення_активності', models.DateField()),
                ('Кількість_разів_на_тиждень', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='R7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Тип_активності', models.CharField(max_length=100)),
                ('Тривалість', models.DurationField()),
                ('Кількість_спалених_калорій', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='R8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Назва_тренування', models.CharField(max_length=100)),
                ('Опис_тренування', models.TextField()),
                ('Домінуюча_група_м_язів', models.CharField(max_length=100)),
                ('Кількість_повторів', models.IntegerField()),
                ('Кількість_підходів', models.IntegerField()),
                ('Необхідне_обладнання', models.TextField()),
                ('Кількість_калорій', models.IntegerField()),
                ('Вміст_білків', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='R9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Кількість_повторів', models.IntegerField()),
                ('Кількість_підходів', models.IntegerField()),
                ('Рівень_складності', models.CharField(max_length=50)),
            ],
        ),
    ]
