# Generated by Django 5.0.4 on 2024-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='r6',
            name='Тренування',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
